on: push
name: Continuous Delivery 
jobs:
  pushNightlyDocker:
    name: Build Nightly Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Docker Hub
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build Nightly Docker images
      run: |
        docker build -t difegue/lanraragi:nightly -f ./tools/DockerSetup/Dockerfile .
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker build -t difegue/lanraragi:nightly-arm -f ./tools/DockerSetup/Dockerfile.arm .
    - name: Push nightly to Docker Hub
      run: |
        docker push difegue/lanraragi:nightly
        docker push difegue/lanraragi:nightly-arm
  pushNightlyWSL:
    name: Build Nightly Windows Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Untagged Docker Build
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: build -t difegue/lanraragi -f ./tools/DockerSetup/Dockerfile .
    - name: Build WSL zip
      uses: ./.github/action-wslbuild
    - name: Upload Installer to MEGA
      uses: difegue/action-megacmd@master
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
        USERNAME: ${{ secrets.USERNAME }}
      with:
        args: put -c LANraragi_Windows_Installer.zip Windows_Nightlies/${GITHUB_SHA}/LRR_Nightly_Windows.zip
